#!/usr/bin/python3

"""Handles the entire flow of data both to and from MMM

The controller is meant to be ran directly to execute one of three different
MMM runs.  The different run types the controller supports are:
* Basic Run: MMM is ran once using data obtained from TRANSP.  Various profile
  plot PDFs are created, and all used data is saved to CSVs.  This run is
  fundamental to storing all non-scanned variable data, so a basic run is
  also executed at the start of both variable and control scans.
* Variable Scan: Values of a specified variable are adjusted using a range of
  scan factors, which are multiplicative factors.  MMM is ran once for each
  factor in the scan range.  Valid variables to scan must be members of the
  InputVariables class.
* Control Scan: Values of a specified control are adjusted using a range of
  scan factors, in similar fashion to a variable scan.  Valid controls to
  scan must be members of the InputControls class.

When conducting either a variable or control scan, values of all input,
additional, and output variables are saved to CSV for each factor in the scan
range.  Factor files contain variable data as functions of rmin (or rho),
where each file corresponds to a different scan factor value (noted by the
filename). After the scan is completed, this saved data is then reshaped and
saved again into new rho files, which contain values of each variable type at
a specified point of rho.  Rho files contain variable data as function of the
scanned variable at each point of rho, where each file corresponds to a
different rho value (noted by the filename).

A new scan number is created each time a new run is executed.  This means that
new data generated by MMM will never overwrite previously generated data. The
trade-off of this is that many scan folders can be created over time, and it
is up to the user to maintain the folders as necessary.

In terms of plot generation, the controller only produces plots of base profiles
(unaltered by scan factors).  Plots from data stored in scan factor files or
rho files should be generated by directly running the various modules
provided in the plotting directory.

Example Usage:
* See commands listed at the bottom of this file
"""

# 3rd Party Packages
import numpy as np

# Local Packages
import settings
import modules.controls
import modules.options
import modules.adjustments as adjustments
import modules.datahelper as datahelper
import modules.mmm as mmm
import modules.reshaper as reshaper
import modules.utils as utils
import plotting.modules.profiles as profiles
from modules.enums import ShotType, ScanType, ProfileType


def _execute_variable_scan(mmm_vars, input_controls):
    '''
    Executes an input variable scan, where the values of an input variable are
    varied over a specified range and are then sent to the MMM driver for
    each value of the range

    Create a copy of mmm_vars as modified_vars to keep variables that are
    modified over the course of the scan separate from base MMM input
    variables.  For each factor of the scan_range, we modify the value of the
    specified var_to_scan, and then adjust any dependent variables. The MMM
    driver is ran each time var_to_scan is adjusted, and all input and output
    variable data is saved to a subfolder named after var_to_scan.
    Afterwards, the saved CSV data is reshaped into data dependent on the
    scanned parameter, and is saved to another set of CSV within a new
    subfolder labeled rho.

    Parameter scan PDFs are not produced here, and the output data is intended
    to be plotted by a separate process after the scan is complete.

    Parameters:
    * mmm_vars (InputVariables): Contains all variables needed to write the MMM input file
    * controls (InputControls): Specifies input control values in the MMM input file
    '''

    scan_range = mmm_vars.options.scan_range
    var_to_scan = mmm_vars.options.var_to_scan

    for i, scan_factor in enumerate(scan_range):
        print(f'Executing {var_to_scan} scan: {i + 1} / {len(scan_range)}')
        adjusted_vars = adjustments.adjust_scanned_variable(mmm_vars, scan_factor)
        adjusted_vars.save(scan_factor)
        output_vars = mmm.run_wrapper(adjusted_vars, controls)
        output_vars.save(scan_factor)


def _execute_control_scan(mmm_vars, controls):
    '''
    Executes an input control scan, where the values of an input control are
    varied over a specified range and are then sent to the MMM driver for
    each value of the range

    Parameter scan PDFs are not produced here, and the output data is intended
    to be plotted by a separate process after the scan is complete.

    Parameters:
    * mmm_vars (InputVariables): Contains all variables needed to write MMM input file
    * controls (InputControls): Specifies input control values in the MMM input file
    '''

    # Create a reference to control being scanned in InputControls. Modifying
    # scanned_control values will modify its corresponding values in
    # adjusted_controls

    scan_range = mmm_vars.options.scan_range
    var_to_scan = mmm_vars.options.var_to_scan

    adjusted_controls = datahelper.deepcopy_data(controls)
    scanned_control = adjusted_controls.get_scanned_control()
    base_control = controls.get_scanned_control()

    for i, scan_factor in enumerate(scan_range):
        print(f'Executing {var_to_scan} scan: {i + 1} / {len(scan_range)}')
        scanned_control.values = scan_factor * base_control.values
        mmm_vars.save(scan_factor)
        adjusted_controls.save(scan_factor)
        output_vars = mmm.run_wrapper(mmm_vars, adjusted_controls)
        output_vars.save(scan_factor)


def main(scanned_vars, controls):
    '''
    Runs the controller for MMM

    Needed output folders are created and a unique scan number is chosen for
    storing output data. All input variable objects are initialized and
    corresponding plot PDFs are created.  The MMM driver is then ran once,
    and then an optional variable scan can be ran afterwards.

    Parameters:
    * scanned_vars (Dict): Dictionary of variables being scanned
        - keys (str | None): The variable being scanned
        - values (np.ndarray | None): The range of factors to scan over
    * controls (InputControls): Specifies input control values in the MMM input file
    '''

    utils.init_logging()
    options = controls.options  # Creates a reference

    # TODO: Add validation for all items in scanned_vars
    for var_to_scan, scan_range in scanned_vars.items():
        options.scan_num = utils.get_scan_num(options.runid)
        options.set(var_to_scan=var_to_scan, scan_range=scan_range)

        print(f'\nRunning MMM Controller for {options.runid}, scan {options.scan_num}...')

        utils.init_output_dirs(options)

        mmm_vars, cdf_vars, __ = datahelper.initialize_variables(options)
        output_vars = mmm.run_wrapper(mmm_vars, controls)

        options.save()
        controls.save()
        mmm_vars.save()
        output_vars.save()

        if settings.MAKE_PROFILE_PDFS:
            profiles.plot_profiles(ProfileType.INPUT, mmm_vars)
            profiles.plot_profiles(ProfileType.ADDITIONAL, mmm_vars)
            profiles.plot_profiles(ProfileType.COMPARED, mmm_vars, cdf_vars)
            profiles.plot_profiles(ProfileType.OUTPUT, output_vars)

        # Variable and control scans
        if options.scan_type.value:
            if options.scan_type is ScanType.VARIABLE:
                _execute_variable_scan(mmm_vars, controls)
            elif options.scan_type is ScanType.CONTROL:
                _execute_control_scan(mmm_vars, controls)

            reshaper.create_rho_files(options)
            print(f'\nScan complete: {options.runid}, scan {options.scan_num}, {options.var_to_scan}\n')


# Run this file directly to plot variable profiles and run the MMM driver
if __name__ == '__main__':
    scanned_vars = {}

    '''
    TRANSP Data:
    * Uncomment the line you wish to use
    '''
    # runid, shot_type, input_time = '120968A02', ShotType.NSTX, 0.5
    # runid, shot_type, input_time = '120982A09', ShotType.NSTX, 0.5
    # runid, shot_type, input_time = '129041A10', ShotType.NSTX, 0.5
    # runid, shot_type, input_time = '138536A01', ShotType.NSTX, 0.630
    # runid, shot_type, input_time = '132017T01', ShotType.DIII_D, 2.1
    # runid, shot_type, input_time = '141552A01', ShotType.DIII_D, 2.1
    runid, shot_type, input_time = 'TEST', ShotType.NSTX, 0.5

    '''
    Scanned Variables:
    * Uncomment the lines you wish to include in scanned_vars
    * Using None as the scanned variable will just run MMM once
    '''
    # scanned_vars[None] = None
    # scanned_vars['etgm_kyrhoe'] = np.arange(start=0.5, stop=5 + 1e-6, step=0.5)

    # scanned_vars['betae'] = np.arange(start=0.05, stop=6 + 1e-6, step=0.05)
    # scanned_vars['btor'] = np.arange(start=0.025, stop=3 + 1e-6, step=0.025)
    # scanned_vars['etae'] = np.arange(start=0.025, stop=3 + 1e-6, step=0.025)
    # scanned_vars['etgm_kyrhos'] = np.arange(start=0.05, stop=6 + 1e-6, step=0.05)
    # scanned_vars['gne'] = np.arange(start=0.025, stop=3 + 1e-6, step=0.025)
    # scanned_vars['gnz'] = np.arange(start=0.05, stop=9 + 1e-6, step=0.05)
    # scanned_vars['gte'] = np.arange(start=0.025, stop=6 + 1e-6, step=0.05)
    # scanned_vars['nuei'] = np.arange(start=0.025, stop=3 + 1e-6, step=0.025)
    # scanned_vars['q'] = np.arange(start=0.6, stop=2.4 + 1e-6, step=0.015)
    # scanned_vars['shear'] = np.arange(start=-6.0, stop=6 + 1e-6, step=0.1)
    # scanned_vars['tau'] = np.arange(start=0.025, stop=3 + 1e-6, step=0.025)
    # scanned_vars['zeff'] = np.arange(start=0.02, stop=4 + 1e-6, step=0.02)**2

    scanned_vars['etgm_kyrhoe'] = np.arange(start=0.02, stop=12 + 1e-6, step=0.02)

    '''
    Options:
    * input_points is the number of points to use when making the MMM input file
    * Set input_points = None to match the number of points used in the CDF
    * Set uniform_rho = True to interpolate to a grid of evenly spaced rho values (takes longer)
    * apply_smoothing enables smoothing of all variables that have a smooth value set in the Variables class
    '''
    options = modules.options.Options(
        runid=runid,
        shot_type=shot_type,
        input_time=input_time,
        input_points=101,
        uniform_rho=1,
        apply_smoothing=1,
    )

    '''
    Input Controls:
    * cmodel enables (disables) the corresponding model if set to 1 (0)
    '''
    controls = modules.controls.InputControls(
        options,
        cmodel_weiland=0,
        cmodel_dribm=0,
        cmodel_etg=0,
        cmodel_etgm=1,
        cmodel_mtm=0,
        etgm_kyrhoe=0.25,
        etgm_kyrhos=0.33,
        etgm_cl=1,  # etgm_cl=0 is collisionless, etgm_cl=1 is collisional
        etgm_exbs=0,
        etgm_kyrhoe_scan=0,
        etgm_use_gne_in=1,
    )

    settings.AUTO_OPEN_PDFS = 0
    settings.MAKE_PROFILE_PDFS = 0

    main(scanned_vars, controls)
